rss_feeds:
  - https://www.coindesk.com/arc/outboundfeeds/rss/
  - https://www.theblock.co/rss
  - https://cointelegraph.com/rss
  - https://decrypt.co/feed
  - https://www.bankless.com/feed
  - https://cryptoslate.com/feed/
  - https://bitcoinmagazine.com/.rss/full/
  - https://www.reddit.com/r/CryptoCurrency/.rss